import sqlite3
import os
from collections import defaultdict

db_path = ".codegraph/codegraph.db"
output_path = "docs/codegraph_index.md"

if not os.path.exists(db_path):
    print(f"Error: {db_path} not found. Please run 'codegraph init -i' first.")
    exit(1)

conn = sqlite3.connect(db_path)
cursor = conn.cursor()

markdown_content = []
markdown_content.append("# Project Logical Index (Generated by CodeGraph)\n")
markdown_content.append("This document provides a logical index of the codebase, including file structure, key classes, routes, and components, to help understand the project structure and flow with minimal token usage.\n")

# 1. Project Overview & Stats
markdown_content.append("## 📊 Codebase Statistics\n")
cursor.execute("SELECT COUNT(*) FROM files;")
total_files = cursor.fetchone()[0]

cursor.execute("SELECT COUNT(*) FROM nodes;")
total_nodes = cursor.fetchone()[0]

cursor.execute("SELECT COUNT(*) FROM edges;")
total_edges = cursor.fetchone()[0]

markdown_content.append(f"- **Total Files:** {total_files}\n")
markdown_content.append(f"- **Total Semantic Nodes:** {total_nodes}\n")
markdown_content.append(f"- **Total Relationships (Edges):** {total_edges}\n\n")

markdown_content.append("### Nodes by Type\n")
cursor.execute("SELECT kind, COUNT(*) FROM nodes GROUP BY kind ORDER BY COUNT(*) DESC;")
for kind, count in cursor.fetchall():
    markdown_content.append(f"- **{kind}:** {count}\n")
markdown_content.append("\n")

# 2. Key Directories / Components
markdown_content.append("## 📁 Core Directory Structure\n")
# Group files by top-level and second-level directory
dir_groups = defaultdict(int)
cursor.execute("SELECT file_path FROM nodes WHERE kind='file';")
for (file_path,) in cursor.fetchall():
    if not file_path:
        continue
    parts = file_path.split('/')
    if len(parts) >= 2:
        dir_groups[f"{parts[0]}/{parts[1]}"] += 1
    elif len(parts) == 1:
        dir_groups[parts[0]] += 1

for folder, count in sorted(dir_groups.items(), key=lambda x: x[0]):
    markdown_content.append(f"- `/{folder}` ({count} files)\n")
markdown_content.append("\n")

# 3. HTTP / API Routes
markdown_content.append("## 🌐 HTTP API Routes (Backend)\n")
markdown_content.append("Routes defined in `server/src/`:\n\n")
cursor.execute("SELECT name, file_path, start_line FROM nodes WHERE kind='route' ORDER BY name;")
routes = cursor.fetchall()
if routes:
    markdown_content.append("| Route Pattern / Handler | File Path | Line |\n")
    markdown_content.append("| :--- | :--- | :--- |\n")
    for name, file_path, line in routes:
        markdown_content.append(f"| `{name}` | [{os.path.basename(file_path)}](file://{os.path.abspath(file_path)}#L{line}) | {line} |\n")
else:
    markdown_content.append("No explicit HTTP routes resolved in the graph.\n")
markdown_content.append("\n")

# 4. Key Classes
markdown_content.append("## 📦 Class Directory (OOP Interfaces)\n")
markdown_content.append("Key classes representing domain logic, adapters, or services:\n\n")
cursor.execute("SELECT name, qualified_name, file_path, start_line FROM nodes WHERE kind='class' ORDER BY name;")
classes = cursor.fetchall()
if classes:
    markdown_content.append("| Class Name | Qualified Name | File Path | Line |\n")
    markdown_content.append("| :--- | :--- | :--- | :--- |\n")
    for name, q_name, file_path, line in classes:
        markdown_content.append(f"| **{name}** | `{q_name}` | [{os.path.basename(file_path)}](file://{os.path.abspath(file_path)}#L{line}) | {line} |\n")
else:
    markdown_content.append("No classes found.\n")
markdown_content.append("\n")

# 5. Interfaces & Types (Data Schema & Contracts)
markdown_content.append("## 📝 Key Data Interfaces & Types\n")
markdown_content.append("Key interfaces from `shared/` and module types:\n\n")
cursor.execute("SELECT name, file_path, start_line FROM nodes WHERE kind='interface' AND (file_path LIKE '%shared%' OR file_path LIKE '%types%') LIMIT 50;")
interfaces = cursor.fetchall()
if interfaces:
    markdown_content.append("| Interface Name | File Path | Line |\n")
    markdown_content.append("| :--- | :--- | :--- |\n")
    for name, file_path, line in interfaces:
        markdown_content.append(f"| `{name}` | [{os.path.basename(file_path)}](file://{os.path.abspath(file_path)}#L{line}) | {line} |\n")
else:
    markdown_content.append("No shared interfaces found.\n")
markdown_content.append("\n")

# 6. Critical Cross-Module Call Relationships
markdown_content.append("## 🔗 Cross-Module Call Relationships (Top 50)\n")
markdown_content.append("Top symbol calling relations to understand interaction flow:\n\n")
cursor.execute("""
    SELECT DISTINCT s.name, s.kind, s.file_path, t.name, t.kind, t.file_path
    FROM edges e
    JOIN nodes s ON e.source = s.id
    JOIN nodes t ON e.target = t.id
    WHERE e.kind = 'calls' 
      AND s.file_path != t.file_path 
      AND s.kind IN ('function', 'method')
      AND t.kind IN ('function', 'method', 'class')
    LIMIT 50;
""")
calls = cursor.fetchall()
if calls:
    markdown_content.append("| Caller (Source) | Caller File | Calls -> | Callee (Target) | Callee File |\n")
    markdown_content.append("| :--- | :--- | :--- | :--- | :--- |\n")
    for s_name, s_kind, s_file, t_name, t_kind, t_file in calls:
        s_base = os.path.basename(s_file) if s_file else "unknown"
        t_base = os.path.basename(t_file) if t_file else "unknown"
        markdown_content.append(f"| `{s_name}` ({s_kind}) | {s_base} | ➔ | `{t_name}` ({t_kind}) | {t_base} |\n")
else:
    markdown_content.append("No cross-file call relationships resolved.\n")

conn.close()

# Write markdown
os.makedirs(os.path.dirname(output_path), exist_ok=True)
with open(output_path, 'w', encoding='utf-8') as f:
    f.writelines(markdown_content)

print(f"Success: Logic index generated at {output_path}")
